### PR TITLE
Add get_traffic_meter

### PR DESCRIPTION
**Pull request by yorickvP**
I downloaded the netgear genie app and ran it in wine to 
reverse-engineer GetTrafficMeterStatistics. This gives 
statistics about the internet traffic (when enabled in 
the interface).

I only tested this in python3, for now.

### CODE REVIEW

**Comment by yorickvP** [comment]
It works in python2 as well.

**Comment by balloob** [comment]
Looks good! :dolphin:

**Comment by gruijter** [comment]
@balloob @yorickvP Any chance you can also reverse engineer to enable/disable the internet connection of a connected device? If you manage to add this I can build some nice use cases when integrating into home automation (e.g. block my son's ipad internet after 10pm)

Secondly: do you know anyone who can port the python to javascript/nodejs?

**Comment by yorickvP** [comment]
@gruijter I think the routers *might* have that functionality builtin.

I could port it to javascript/nodejs, but I don't have enough time to do it on a voluntary basis. I might be available for hire. Same goes for the reverse-engineering (provided you can disconnect things using that api).

**Comment by gruijter** [comment]
Hi @yorickvP , thx 4 the offer, but was hoping that some enthousiast finds some spare time to do this 🤗

I did find an old javascript port on github from @ryanthejuggler that can maybe be a good starting point : https://github.com/ryanthejuggler/node-netgear

**Pull request merged**
